//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProductBASEEEntities4 : DbContext
    {
        public ProductBASEEEntities4()
            : base("name=ProductBASEEEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Author> Author { get; set; }
        public virtual DbSet<Personne> Personne { get; set; }
        public virtual DbSet<Personnne> Personnne { get; set; }
        public virtual DbSet<Product> Product { get; set; }
        public virtual DbSet<ShopProd> ShopProd { get; set; }
        public virtual DbSet<Table> Table { get; set; }
    }
}
