//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int idpr { get; set; }
        public string productName { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public Nullable<int> price { get; set; }
        public string authorname { get; set; }
        public string imgUrl { get; set; }
    }
}
